#include <stdio.h>

int main() {

    // n will store which God number we want (1st, 2nd, 10th, etc.)
    int n;
    scanf("%d", &n);   // Take input from user

    /*
        We create an array to store God numbers.
        Size is n because we only need first n God numbers.
    */
    int god[n];

    /*
        By definition:
        The first God number is always 1.
    */
    god[0] = 1;

    /*
        These indexes keep track of:
        - which number should be multiplied by 2
        - which number should be multiplied by 3
        - which number should be multiplied by 5
    */
    int i2 = 0, i3 = 0, i5 = 0;

    /*
        These store the next possible God numbers
        generated by multiplying with 2, 3, and 5
    */
    int next2 = 2;   // god[0] * 2
    int next3 = 3;   // god[0] * 3
    int next5 = 5;   // god[0] * 5

    /*
        Loop to generate God numbers from index 1 to n-1
        (because index 0 already contains 1)
    */
    for (int i = 1; i < n; i++) {

        /*
            Find the smallest among next2, next3, and next5
            That smallest value will be the next God number
        */
        int nextGod = next2;

        if (next3 < nextGod)
            nextGod = next3;

        if (next5 < nextGod)
            nextGod = next5;

        // Store the next God number in array
        god[i] = nextGod;

        /*
            Now update the indexes and next values.
            We use separate IFs (not else-if) to avoid duplicates.
            Example: 6 comes from both 2×3 and 3×2
        */

        if (nextGod == next2) {
            i2++;                       // Move pointer for 2
            next2 = god[i2] * 2;        // Generate next multiple of 2
        }

        if (nextGod == next3) {
            i3++;                       // Move pointer for 3
            next3 = god[i3] * 3;        // Generate next multiple of 3
        }

        if (nextGod == next5) {
            i5++;                       // Move pointer for 5
            next5 = god[i5] * 5;        // Generate next multiple of 5
        }
    }

    /*
        The n-th God number is stored at index n-1
        (because array index starts from 0)
    */
    printf("%d", god[n - 1]);

    return 0;   // End of program
}
